version: '3.8'

services:
  # Django Web Application (Retail Eureka Dashboard)
  django-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-platform
    ports:
      - "8502:8700"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=retail_eureka
      - DB_USER=aisupply
      - DB_PASSWORD=H6.yLBweMW1w\$$P&ub60
      - DB_HOST=aisupply.rc
      - DB_PORT=5432
      - FABRIC_API_URL=http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "aisupply.rc:host-gateway"
