// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductManagement.DbContexts;

#nullable disable

namespace ProductManagement.Migrations
{
    [DbContext(typeof(ProductManagementContext))]
    [Migration("20240712082532_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.Entity.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Name = "Sebze"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            Name = "Meyve"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            Name = "Kuru Meyve"
                        });
                });

            modelBuilder.Entity("ProductManagement.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("DiscountedPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sale")
                        .HasColumnType("double precision");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            FileId = 1L,
                            IsDeleted = false,
                            Name = "Soğan Kuru Dökme Kg",
                            Price = 9.9000000000000004,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            FileId = 2L,
                            IsDeleted = false,
                            Name = "Hatay Arsuz Limonu Kg",
                            Price = 17.949999999999999,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2L,
                            FileId = 3L,
                            IsDeleted = false,
                            Name = "Muz Yerli Kg",
                            Price = 51.899999999999999,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2L,
                            FileId = 4L,
                            IsDeleted = false,
                            Name = "Portakal Sıkma File Kg",
                            Price = 16.899999999999999,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            FileId = 5L,
                            IsDeleted = false,
                            Name = "Maydonoz Adet",
                            Price = 15.949999999999999,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 1L,
                            FileId = 6L,
                            IsDeleted = false,
                            Name = "Hıyar Badem Paket Kg",
                            Price = 44.950000000000003,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 2L,
                            FileId = 7L,
                            IsDeleted = false,
                            Name = "Mandalina Murcot",
                            Price = 39.950000000000003,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 1L,
                            FileId = 8L,
                            IsDeleted = false,
                            Name = "Domates Kokteyl Kg",
                            Price = 69.950000000000003,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 2L,
                            FileId = 9L,
                            IsDeleted = false,
                            Name = "Elma Starking Kg",
                            Price = 34.899999999999999,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 3L,
                            FileId = 10L,
                            IsDeleted = false,
                            Name = "Kabak Sakız Kg",
                            Price = 34.950000000000003,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 3L,
                            FileId = 11L,
                            IsDeleted = false,
                            Name = "Domates Salkım Kg",
                            Price = 49.950000000000003,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("ProductManagement.Entity.ProductComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryRating")
                        .HasColumnType("integer");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityRating")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("VendorRating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProductManagement.Entity.ProductStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<double>("Stock")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            ProductId = 1L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            ProductId = 2L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            ProductId = 3L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 4L,
                            IsDeleted = false,
                            ProductId = 4L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 5L,
                            IsDeleted = false,
                            ProductId = 5L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 6L,
                            IsDeleted = false,
                            ProductId = 6L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 7L,
                            IsDeleted = false,
                            ProductId = 7L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 8L,
                            IsDeleted = false,
                            ProductId = 8L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 9L,
                            IsDeleted = false,
                            ProductId = 9L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 10L,
                            IsDeleted = false,
                            ProductId = 10L,
                            Stock = 100.0
                        },
                        new
                        {
                            Id = 11L,
                            IsDeleted = false,
                            ProductId = 11L,
                            Stock = 100.0
                        });
                });

            modelBuilder.Entity("ProductManagement.Entity.Product", b =>
                {
                    b.HasOne("ProductManagement.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagement.Entity.ProductComment", b =>
                {
                    b.HasOne("ProductManagement.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductManagement.Entity.ProductStock", b =>
                {
                    b.HasOne("ProductManagement.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
