# Generated by Django 5.2.7 on 2026-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.IntegerField(verbose_name='Block Height')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.CharField(max_length=100, verbose_name='Batch ID')),
                ('data_hash', models.CharField(max_length=64, verbose_name='Data Hash (SHA256)')),
                ('previous_hash', models.CharField(max_length=64, verbose_name='Previous Hash')),
                ('block_hash', models.CharField(max_length=64, unique=True, verbose_name='Block Hash')),
                ('signer', models.CharField(max_length=100, verbose_name='Signer Wallet/ID')),
                ('role', models.CharField(max_length=50, verbose_name='User Role')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('data_content', models.JSONField(verbose_name='Block Data (JSON)')),
            ],
            options={
                'verbose_name': 'Blockchain Block',
                'verbose_name_plural': 'Blockchain Blocks',
                'db_table': 'blockchain_blocks',
                'ordering': ['block_index'],
            },
        ),
    ]
