# Generated by Django 5.2.7 on 2025-12-17 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricEnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_usage', models.CharField(max_length=100, verbose_name='Principal uso')),
                ('total_consumption_kwh_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo total (kWh/ano)')),
                ('percent_grid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% rede elétrica')),
                ('percent_photovoltaic', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% fotovoltaico próprio')),
                ('percent_other_renewable', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% outra renovável')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'db_table': 'event_electric_energy',
            },
        ),
        migrations.CreateModel(
            name='FertilizerOrganicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organic_fertilizer_type', models.CharField(max_length=100, verbose_name='Tipo de Fertilizante Orgânico')),
                ('origin', models.CharField(max_length=50, verbose_name='Origem (pecuária, composto, etc.)')),
                ('n_content_kgt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Teor N (kg/t ou %)')),
                ('p_content_kgt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Teor P (kg/t ou %)')),
                ('k_content_kgt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Teor K (kg/t ou %)')),
                ('dose_tha_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose (t/ha/ano)')),
                ('application_mode', models.CharField(max_length=100, verbose_name='Modo de Aplicação')),
            ],
            options={
                'db_table': 'event_fertilizer_organic',
            },
        ),
        migrations.CreateModel(
            name='FertilizerSyntheticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_product', models.CharField(max_length=100, verbose_name='Produto Comercial')),
                ('form_npk', models.CharField(max_length=50, verbose_name='Forma (NPK, etc.)')),
                ('n_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor N (%)')),
                ('p2o5_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor P₂O₅ (%)')),
                ('k2o_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor K₂O (%)')),
                ('total_dose_kg_ha_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose Total (kg/ha/ano)')),
                ('num_applications', models.IntegerField(verbose_name='Nº de Aplicações')),
                ('application_season', models.CharField(max_length=50, verbose_name='Épocas de Aplicação (mês)')),
            ],
            options={
                'db_table': 'event_fertilizer_synthetic',
            },
        ),
        migrations.CreateModel(
            name='FuelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Tipo de combustível')),
                ('annual_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo anual')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('main_usage_season', models.CharField(max_length=100, verbose_name='Época principal de uso')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'db_table': 'event_fuel',
            },
        ),
        migrations.CreateModel(
            name='IrrigationWaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_source', models.CharField(max_length=100, verbose_name='Fonte de água')),
                ('volume_m3_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (m³/ano)')),
                ('extraction_method', models.CharField(max_length=100, verbose_name='Método de captação')),
                ('pumping_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura de bombagem (m)')),
                ('irrigation_system', models.CharField(max_length=100, verbose_name='Sistema de rega')),
                ('estimated_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eficiência estimada (%)')),
            ],
            options={
                'db_table': 'event_irrigation_water',
            },
        ),
        migrations.CreateModel(
            name='MachineryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery_type', models.CharField(max_length=100, verbose_name='Tipo de maquinaria')),
                ('main_operation', models.CharField(max_length=100, verbose_name='Principal operação')),
                ('hours_per_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nº horas/ano')),
                ('power', models.CharField(max_length=50, verbose_name='Potência (kW ou CV)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'db_table': 'event_machinery',
            },
        ),
        migrations.CreateModel(
            name='PestControlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_product', models.CharField(max_length=100, verbose_name='Produto Comercial')),
                ('active_substance', models.CharField(max_length=100, verbose_name='Substância Ativa')),
                ('pest_type', models.CharField(max_length=100, verbose_name='Tipo (fungicida, inseticida, etc.)')),
                ('dose_per_application', models.CharField(max_length=50, verbose_name='Dose (kg ou L/ha/aplicação)')),
                ('num_applications_year', models.IntegerField(verbose_name='Nº aplicações/ano')),
                ('application_mode', models.CharField(max_length=100, verbose_name='Modo de aplicação')),
            ],
            options={
                'db_table': 'event_pest_control',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='Marca do Sensor')),
                ('sensor_type', models.CharField(choices=[('Temperature', 'Temperatura'), ('Humidity', 'Humidade'), ('Light', 'Luminosidade'), ('Gas', 'Gás/CO2')], max_length=50, verbose_name='Tipo de Sensor')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SoilCorrectiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_product', models.CharField(max_length=100, verbose_name='Produto Comercial')),
                ('corrective_type', models.CharField(max_length=100, verbose_name='Tipo (calcário, dolomite, gesso, etc.)')),
                ('caco3_content', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Teor CaCO₃ equivalente (%)')),
                ('dose_kg_ha_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose (kg/ha/ano)')),
                ('frequency_years', models.IntegerField(verbose_name='Frequência (anos)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'db_table': 'event_soil_corrective',
            },
        ),
        migrations.CreateModel(
            name='PlantationPlan',
            fields=[
                ('plantation_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_of_seeds', models.IntegerField(verbose_name='Nº de Sementes Plantadas')),
                ('production_type', models.CharField(choices=[('Modern', 'Moderna'), ('Traditional', 'Tradicional')], max_length=20, verbose_name='Tipo de Produção')),
                ('chemical_use', models.CharField(choices=[('Yes', 'Sim'), ('No', 'Não')], max_length=5, verbose_name='Uso de Químicos')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('location', models.CharField(max_length=100)),
                ('plantation_date', models.DateField(verbose_name='Data de Plantação')),
                ('total_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área total do pomar (m²)')),
                ('avg_plant_age_years', models.IntegerField(blank=True, null=True, verbose_name='Average age of plants (years)')),
                ('kiwi_variety', models.CharField(blank=True, choices=[('Hayward', 'Hayward'), ('Actinidia deliciosa', 'Actinidia deliciosa')], max_length=50, null=True, verbose_name='Variedade de Kiwi')),
                ('rootstock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Porta-enxerto (se aplicável)')),
                ('density_plants_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidade de plantação (plantas/m²)')),
                ('conduct_system', models.CharField(blank=True, choices=[('T-bar', 'T-bar'), ('Pergola', 'Pérgola')], max_length=50, null=True, verbose_name='Sistema de condução')),
                ('soil_type', models.CharField(blank=True, choices=[('Clay', 'Argiloso'), ('Sand', 'Arenoso'), ('Loam', 'Franco')], max_length=50, null=True, verbose_name='Tipo de solo')),
                ('ph_soil', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH do solo')),
                ('organic_matter_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Matéria orgânica do solo (%)')),
                ('water_regime', models.CharField(blank=True, choices=[('Total', 'Rega Total'), ('Supp', 'Suplementar'), ('Dry', 'Sequeiro')], max_length=20, null=True, verbose_name='Regime hídrico')),
                ('irrigation_system', models.CharField(blank=True, choices=[('Drip', 'Gota-a-gota'), ('Sprinkler', 'Aspersão')], max_length=50, null=True, verbose_name='Tipo de sistema de rega')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantation_plan',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField(verbose_name='Data de Colheita')),
                ('harvest_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Colhida (Kg)')),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Entregue (Kg)')),
                ('avg_quality_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Qualidade Média (1-10)')),
                ('utilized_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Aproveitada (Kg)')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_records', to='dashboard.plantationplan', verbose_name='Plano de Plantação')),
            ],
            options={
                'db_table': 'harvest_records',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda (€)')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='plantationplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.product'),
        ),
        migrations.CreateModel(
            name='SoilCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('sub_category', models.CharField(max_length=100, verbose_name='Sub-Categoria')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
            ],
            options={
                'db_table': 'soil_characteristic',
                'unique_together': {('category', 'sub_category', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='PlantationSoilValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Registado')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_values', to='dashboard.plantationplan')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.soilcharacteristic')),
            ],
            options={
                'db_table': 'plantation_soil_value',
                'unique_together': {('plantation', 'characteristic')},
            },
        ),
        migrations.AddField(
            model_name='plantationplan',
            name='soil_characteristics',
            field=models.ManyToManyField(related_name='plantations', through='dashboard.PlantationSoilValue', to='dashboard.soilcharacteristic'),
        ),
        migrations.CreateModel(
            name='PlantationEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='Data do Evento')),
                ('event_type', models.CharField(choices=[('Fert_Min', 'Fertilizantes (sintéticos minerais)'), ('Fert_Org', 'Fertilizantes (orgânicos)'), ('Soil_Corr', 'Corretivos do solo'), ('Pest', 'Produtos fitofarmacêuticos'), ('Machine_Hrs', 'Horas de utilização da maquinaria'), ('Fuel', 'Combustíveis'), ('Electric', 'Energia elétrica'), ('Water', 'Água de rega')], max_length=50, verbose_name='Tipo de Evento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas/Descrição')),
                ('electric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_electric', to='dashboard.electricenergydata')),
                ('fertilizer_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_org', to='dashboard.fertilizerorganicdata')),
                ('fertilizer_synth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_synth', to='dashboard.fertilizersyntheticdata')),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fuel', to='dashboard.fueldata')),
                ('machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_machinery', to='dashboard.machinerydata')),
                ('pest_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_pest', to='dashboard.pestcontroldata')),
                ('water', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_water', to='dashboard.irrigationwaterdata')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.plantationplan', verbose_name='Plano de Plantação')),
                ('soil_corrective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_soil', to='dashboard.soilcorrectivedata')),
            ],
            options={
                'db_table': 'plantation_events',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telemóvel')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada Completa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('control_type', models.CharField(choices=[('Controlled', 'Controlado'), ('Non-Controlled', 'Não Controlado')], max_length=20, verbose_name='Tipo de Armazém')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade (m² ou Kg)')),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'Producer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono/Perfil')),
                ('sensors', models.ManyToManyField(blank=True, to='dashboard.sensor', verbose_name='Sensores Instalados')),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
    ]
