# Generated by Django 5.2.7 on 2025-11-12 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationPlan',
            fields=[
                ('plantation_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_of_seeds', models.IntegerField(verbose_name='Nº de Sementes Plantadas')),
                ('production_type', models.CharField(choices=[('Modern', 'Moderna'), ('Traditional', 'Tradicional')], max_length=20, verbose_name='Tipo de Produção')),
                ('chemical_use', models.CharField(choices=[('Yes', 'Sim'), ('No', 'Não')], max_length=5, verbose_name='Uso de Químicos')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('plantation_date', models.DateField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantation plan',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField(verbose_name='Data de Colheita')),
                ('harvest_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Colhida (Kg)')),
                ('avg_quality_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Qualidade Média (1-10)')),
                ('utilized_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Aproveitada (Kg)')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plantation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.plantationplan', verbose_name='Plano de Plantação Concluído')),
            ],
            options={
                'db_table': 'harvest',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda (€)')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='plantationplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.product'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telemóvel')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada Completa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
