# Generated by Django 5.2.7 on 2025-12-21 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricEnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_usage', models.CharField(max_length=100, verbose_name='Main Usage')),
                ('total_consumption_kwh_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Consumption (kWh/year)')),
                ('percent_grid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Grid')),
                ('percent_photovoltaic', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Photovoltaic (Self)')),
                ('percent_other_renewable', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Other Renewable')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'event_electric_energy',
            },
        ),
        migrations.CreateModel(
            name='FertilizerOrganicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organic_fertilizer_type', models.CharField(max_length=100, verbose_name='Organic Fertilizer Type')),
                ('origin', models.CharField(max_length=50, verbose_name='Origin (livestock, compost, etc.)')),
                ('n_content_kgt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='N Content (kg/t or %)')),
                ('p_content_kgt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='P Content (kg/t or %)')),
                ('k_content_kgt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='K Content (kg/t or %)')),
                ('dose_tha_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose (t/ha/year)')),
                ('application_mode', models.CharField(max_length=100, verbose_name='Application Mode')),
            ],
            options={
                'db_table': 'event_fertilizer_organic',
            },
        ),
        migrations.CreateModel(
            name='FertilizerSyntheticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_product', models.CharField(max_length=100, verbose_name='Commercial Product')),
                ('form_npk', models.CharField(max_length=50, verbose_name='Form (NPK, etc.)')),
                ('n_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='N Content (%)')),
                ('p2o5_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='P2O5 Content (%)')),
                ('k2o_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='K2O Content (%)')),
                ('total_dose_kg_ha_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Dose (kg/ha/year)')),
                ('num_applications', models.IntegerField(verbose_name='No. of Applications')),
                ('application_season', models.CharField(max_length=50, verbose_name='Application Season (month)')),
            ],
            options={
                'db_table': 'event_fertilizer_synthetic',
            },
        ),
        migrations.CreateModel(
            name='FuelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Fuel Type')),
                ('annual_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Consumption')),
                ('unit', models.CharField(max_length=20, verbose_name='Unit')),
                ('main_usage_season', models.CharField(max_length=100, verbose_name='Main Usage Season')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'event_fuel',
            },
        ),
        migrations.CreateModel(
            name='IrrigationWaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_source', models.CharField(max_length=100, verbose_name='Water Source')),
                ('volume_m3_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (m3/year)')),
                ('extraction_method', models.CharField(max_length=100, verbose_name='Extraction Method')),
                ('pumping_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pumping Height (m)')),
                ('irrigation_system', models.CharField(max_length=100, verbose_name='Irrigation System')),
                ('estimated_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimated Efficiency (%)')),
            ],
            options={
                'db_table': 'event_irrigation_water',
            },
        ),
        migrations.CreateModel(
            name='MachineryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery_type', models.CharField(max_length=100, verbose_name='Machinery Type')),
                ('main_operation', models.CharField(max_length=100, verbose_name='Main Operation')),
                ('hours_per_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hours/Year')),
                ('power', models.CharField(max_length=50, verbose_name='Power (kW or CV)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
            ],
            options={
                'db_table': 'event_machinery',
            },
        ),
        migrations.CreateModel(
            name='PestControlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_product', models.CharField(max_length=100, verbose_name='Commercial Product')),
                ('active_substance', models.CharField(max_length=100, verbose_name='Active Substance')),
                ('pest_type', models.CharField(max_length=100, verbose_name='Type (fungicide, insecticide, etc.)')),
                ('dose_per_application', models.CharField(max_length=50, verbose_name='Dose (kg or L/ha/application)')),
                ('num_applications_year', models.IntegerField(verbose_name='No. Applications/Year')),
                ('application_mode', models.CharField(max_length=100, verbose_name='Application Mode')),
            ],
            options={
                'db_table': 'event_pest_control',
            },
        ),
        migrations.CreateModel(
            name='ProductSubFamily',
            fields=[
                ('subfamily_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Subfamília')),
                ('fruit_type', models.CharField(choices=[('Kiwi', 'Kiwi'), ('Apple', 'Maçã')], max_length=50, verbose_name='Tipo de Fruta')),
            ],
            options={
                'db_table': 'product_subfamilies',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='Marca do Sensor')),
                ('sensor_type', models.CharField(choices=[('Temperature', 'Temperatura'), ('Humidity', 'Humidade'), ('Light', 'Luminosidade'), ('Gas', 'Gás/CO2')], max_length=50, verbose_name='Tipo de Sensor')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SoilCorrectiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_product', models.CharField(max_length=100, verbose_name='Commercial Product')),
                ('corrective_type', models.CharField(max_length=100, verbose_name='Type (limestone, dolomite, gypsum, etc.)')),
                ('caco3_content', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CaCO3 Equivalent Content (%)')),
                ('dose_kg_ha_year', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose (kg/ha/year)')),
                ('frequency_years', models.IntegerField(verbose_name='Frequency (years)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
            ],
            options={
                'db_table': 'event_soil_corrective',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda (€)')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PlantationPlan',
            fields=[
                ('plantation_id', models.AutoField(primary_key=True, serialize=False)),
                ('plantation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Plantação')),
                ('quantity_of_trees', models.IntegerField(verbose_name='Quantidade de Árvores')),
                ('production_type', models.CharField(choices=[('Modern', 'Moderna'), ('Traditional', 'Tradicional')], max_length=20, verbose_name='Tipo de Produção')),
                ('chemical_use', models.CharField(choices=[('Yes', 'Sim'), ('No', 'Não')], max_length=5, verbose_name='Uso de Químicos')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('location', models.CharField(max_length=100)),
                ('plantation_date', models.DateField(verbose_name='Data de Plantação')),
                ('total_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área total do pomar (m²)')),
                ('conduct_system', models.CharField(blank=True, choices=[('T-bar', 'T-bar'), ('Pergola', 'Pérgola')], max_length=50, null=True, verbose_name='Sistema de condução')),
                ('soil_type', models.CharField(blank=True, choices=[('Clay', 'Argiloso'), ('Sand', 'Arenoso'), ('Loam', 'Franco')], max_length=50, null=True, verbose_name='Tipo de solo')),
                ('ph_soil', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH do solo')),
                ('organic_matter_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Matéria orgânica do solo (%)')),
                ('water_regime', models.CharField(blank=True, choices=[('Total', 'Rega Total'), ('Supp', 'Suplementar'), ('Dry', 'Sequeiro')], max_length=20, null=True, verbose_name='Regime hídrico')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
            ],
            options={
                'db_table': 'plantation_plan',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Perfil do Requerente')),
                ('order_type', models.CharField(choices=[('BUY', 'Purchase Request (Compra)'), ('SELL', 'Export Offer (Venda/Exportação)')], max_length=10, verbose_name='Tipo de Pedido')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (Kg)')),
                ('warehouse_location', models.CharField(max_length=255, verbose_name='Localização do Armazém')),
                ('status', models.CharField(choices=[('OPEN', 'Open (Aberto)'), ('APPROVED', 'Approved/Fulfilled (Aprovado)')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders_fulfilled', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders_requested', to=settings.AUTH_USER_MODEL)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura')),
            ],
            options={
                'db_table': 'marketplace_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField(verbose_name='Harvest Date')),
                ('harvest_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harvest Quantity (Kg)')),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivered Quantity (Kg)')),
                ('avg_quality_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Average Quality Score (1-10)')),
                ('utilized_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Utilized Quantity (Kg)')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_records', to='dashboard.plantationplan', verbose_name='Plano de Plantação')),
                ('subfamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productsubfamily', verbose_name='Cultura (Subfamília)')),
            ],
            options={
                'db_table': 'harvest_records',
            },
        ),
        migrations.CreateModel(
            name='SoilCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('sub_category', models.CharField(max_length=100, verbose_name='Sub-Categoria')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
            ],
            options={
                'db_table': 'soil_characteristic',
                'unique_together': {('category', 'sub_category', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='PlantationSoilValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Registado')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_values', to='dashboard.plantationplan')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.soilcharacteristic')),
            ],
            options={
                'db_table': 'plantation_soil_value',
                'unique_together': {('plantation', 'characteristic')},
            },
        ),
        migrations.AddField(
            model_name='plantationplan',
            name='soil_characteristics',
            field=models.ManyToManyField(related_name='plantations', through='dashboard.PlantationSoilValue', to='dashboard.soilcharacteristic'),
        ),
        migrations.CreateModel(
            name='PlantationEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_type', models.CharField(choices=[('Fert_Min', 'Fertilizantes (sintéticos minerais)'), ('Fert_Org', 'Fertilizantes (orgânicos)'), ('Soil_Corr', 'Corretivos do solo'), ('Pest', 'Produtos fitofarmacêuticos'), ('Machine_Hrs', 'Horas de utilização da maquinaria'), ('Fuel', 'Combustíveis'), ('Electric', 'Energia elétrica'), ('Water', 'Água de rega')], max_length=50, verbose_name='Event Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Description')),
                ('electric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_electric', to='dashboard.electricenergydata')),
                ('fertilizer_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_org', to='dashboard.fertilizerorganicdata')),
                ('fertilizer_synth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_synth', to='dashboard.fertilizersyntheticdata')),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fuel', to='dashboard.fueldata')),
                ('machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_machinery', to='dashboard.machinerydata')),
                ('pest_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_pest', to='dashboard.pestcontroldata')),
                ('water', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_water', to='dashboard.irrigationwaterdata')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.plantationplan', verbose_name='Plantation Plan')),
                ('subfamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productsubfamily', verbose_name='Culture (Subfamily)')),
                ('soil_corrective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_soil', to='dashboard.soilcorrectivedata')),
            ],
            options={
                'db_table': 'plantation_events',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telemóvel')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada Completa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('control_type', models.CharField(choices=[('Controlled', 'Controlado'), ('Non-Controlled', 'Não Controlado')], max_length=20, verbose_name='Tipo de Armazém')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade (m² ou Kg)')),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'Producer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono/Perfil')),
                ('sensors', models.ManyToManyField(blank=True, to='dashboard.sensor', verbose_name='Sensores Instalados')),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='PlantationCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_plant_age_years', models.IntegerField(blank=True, null=True, verbose_name='Average Age of Plants (years)')),
                ('rootstock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rootstock (if applicable)')),
                ('density_plants_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plantation Density (plants/m²)')),
                ('irrigation_system', models.CharField(blank=True, choices=[('Drip', 'Gota-a-gota'), ('Sprinkler', 'Aspersão')], max_length=50, null=True, verbose_name='Irrigation System Type')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='dashboard.plantationplan', verbose_name='Plano de Plantação')),
                ('subfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura (Subfamília)')),
            ],
            options={
                'db_table': 'plantation_crops',
                'unique_together': {('plantation', 'subfamily')},
            },
        ),
    ]
