# Generated by Django 5.2.7 on 2025-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubFamily',
            fields=[
                ('subfamily_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Subfamília')),
                ('fruit_type', models.CharField(choices=[('Kiwi', 'Kiwi'), ('Apple', 'Maçã')], max_length=50, verbose_name='Tipo de Fruta')),
            ],
            options={
                'db_table': 'product_subfamilies',
            },
        ),
    ]
