# Generated by Django 5.2.7 on 2026-01-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_populate_subfamilies'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.warehouse', verbose_name='Stored In (Warehouse)'),
        ),
    ]
