# Generated by Django 5.2.7 on 2026-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_harvest_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Real de Entrega'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='actual_pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Real de Recolha'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='planned_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista de Entrega'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='planned_pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista de Recolha'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='transport_sensor_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dados dos Sensores (JSON)'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='transport_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Pendente)'), ('PLANNED', 'Planned (Planeado)'), ('IN_TRANSIT', 'In Transit (Em Trânsito)'), ('DELIVERED', 'Delivered (Entregue)')], default='PENDING', max_length=20, verbose_name='Estado do Transporte'),
        ),
    ]
