# Generated by Django 5.2.7 on 2025-12-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_populate_subfamilies'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationplan',
            name='subfamilies',
            field=models.ManyToManyField(related_name='plantations', to='dashboard.productsubfamily', verbose_name='Culturas'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product'),
        ),
    ]
