# Generated by Django 5.2.7 on 2025-12-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_plantationplan_subfamilies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productsubfamily', verbose_name='Cultura (Subfamília)'),
        ),
    ]
