# Generated by Django 5.2.7 on 2026-01-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_marketplaceorder_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='harvest_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders', to='dashboard.harvest', verbose_name='Origem (Colheita)'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='transport_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Pendente)'), ('ACCEPTED', 'Job Accepted (Aceite)'), ('PLANNED', 'Planned (Planeado)'), ('IN_TRANSIT', 'In Transit (Em Trânsito)'), ('DELIVERED', 'Delivered (Entregue)')], default='PENDING', max_length=20, verbose_name='Estado do Transporte'),
        ),
    ]
