# Generated by Django 5.2.7 on 2026-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_marketplaceorder_harvest_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='caliber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Caliber (mm)'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='soluble_solids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Soluble Solids (Brix)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='utilized_quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Waste (Kg)'),
        ),
    ]
