# Generated by Django 5.2.7 on 2025-12-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_plantationevent_subfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantationplan',
            name='avg_plant_age_years',
        ),
        migrations.RemoveField(
            model_name='plantationplan',
            name='density_plants_ha',
        ),
        migrations.RemoveField(
            model_name='plantationplan',
            name='irrigation_system',
        ),
        migrations.RemoveField(
            model_name='plantationplan',
            name='kiwi_variety',
        ),
        migrations.RemoveField(
            model_name='plantationplan',
            name='rootstock',
        ),
        migrations.RemoveField(
            model_name='plantationplan',
            name='subfamilies',
        ),
        migrations.CreateModel(
            name='PlantationCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_plant_age_years', models.IntegerField(blank=True, null=True, verbose_name='Idade média das plantas (anos)')),
                ('variety', models.CharField(blank=True, choices=[('Hayward', 'Hayward'), ('Actinidia deliciosa', 'Actinidia deliciosa')], max_length=50, null=True, verbose_name='Variedade')),
                ('rootstock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Porta-enxerto (se aplicável)')),
                ('density_plants_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidade de plantação (plantas/m²)')),
                ('irrigation_system', models.CharField(blank=True, choices=[('Drip', 'Gota-a-gota'), ('Sprinkler', 'Aspersão')], max_length=50, null=True, verbose_name='Tipo de sistema de rega')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='dashboard.plantationplan', verbose_name='Plano de Plantação')),
                ('subfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura (Subfamília)')),
            ],
            options={
                'db_table': 'plantation_crops',
                'unique_together': {('plantation', 'subfamily')},
            },
        ),
    ]
