# Generated by Django 5.2.7 on 2026-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_harvest_caliber_harvest_soluble_solids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='caliber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Caliber (mm)'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='min_caliber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min Caliber (mm)'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='min_quality_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Min Quality Score (1-10)'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='min_soluble_solids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min Soluble Solids (Brix)'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quality Score (1-10)'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='soluble_solids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Soluble Solids (Brix)'),
        ),
    ]
