# Generated by Django 5.2.7 on 2025-12-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_plantationplan_avg_plant_age_years_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationplan',
            old_name='quantity_of_seeds',
            new_name='quantity_of_trees',
        ),
    ]
