# Generated by Django 5.2.7 on 2026-01-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_marketplaceorder_caliber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processado?'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('Plastic', 'Plástico'), ('Cardboard', 'Cartão'), ('Other', 'Outro')], max_length=50, null=True, verbose_name='Tipo de Embalagem'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='preservation_treatment',
            field=models.CharField(blank=True, choices=[('Natural', 'Tratamento Natural'), ('Conventional', 'Convencional/Químico'), ('None', 'Nenhum')], max_length=50, null=True, verbose_name='Tratamento de Conservação'),
        ),
    ]
