# Generated by Django 5.2.7 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_marketplaceorder_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price / Kg (€)'),
        ),
    ]
