# Generated by Django 5.2.7 on 2025-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_seeds_to_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationplan',
            name='plantation_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Plantação'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='quantity_of_trees',
            field=models.IntegerField(verbose_name='Quantidade de Árvores'),
        ),
    ]
