# Generated by Django 5.2.7 on 2026-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_marketplaceorder_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationplan',
            name='production_type',
            field=models.CharField(choices=[('conventional', 'convencional'), ('integrated', 'produção integrada'), ('organic', 'biológica'), ('regenerative', 'regenerativa'), ('precision', 'precisão'), ('agroforestry', 'agroflorestal')], max_length=20, verbose_name='Tipo de Agricultura'),
        ),
    ]
