# Generated by Django 5.2.7 on 2025-12-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_plantationplan_plantation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantationcrop',
            name='variety',
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='avg_plant_age_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Age of Plants (years)'),
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='density_plants_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plantation Density (plants/m²)'),
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='irrigation_system',
            field=models.CharField(blank=True, choices=[('Drip', 'Gota-a-gota'), ('Sprinkler', 'Aspersão')], max_length=50, null=True, verbose_name='Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='rootstock',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rootstock (if applicable)'),
        ),
    ]
