# Generated by Django 5.2.7 on 2026-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_plantationplan_production_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationplan',
            name='production_type',
            field=models.CharField(choices=[('conventional', 'Convencional'), ('integrated', 'Produção integrada'), ('organic', 'Biológica'), ('regenerative', 'Regenerativa'), ('precision', 'Precisão'), ('agroforestry', 'Agroflorestal')], max_length=20, verbose_name='Tipo de Agricultura'),
        ),
    ]
