# Generated by Django 5.2.7 on 2025-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_plantationcrop_variety_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='avg_quality_score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Average Quality Score (1-10)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='delivered_quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivered Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_date',
            field=models.DateField(verbose_name='Harvest Date'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harvest Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='utilized_quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Utilized Quantity (Kg)'),
        ),
    ]
