# Generated by Django 5.2.7 on 2025-12-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_harvest_avg_quality_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationevent',
            name='event_date',
            field=models.DateField(verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='plantationevent',
            name='event_type',
            field=models.CharField(choices=[('Fert_Min', 'Fertilizantes (sintéticos minerais)'), ('Fert_Org', 'Fertilizantes (orgânicos)'), ('Soil_Corr', 'Corretivos do solo'), ('Pest', 'Produtos fitofarmacêuticos'), ('Machine_Hrs', 'Horas de utilização da maquinaria'), ('Fuel', 'Combustíveis'), ('Electric', 'Energia elétrica'), ('Water', 'Água de rega')], max_length=50, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='plantationevent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes/Description'),
        ),
        migrations.AlterField(
            model_name='plantationevent',
            name='plantation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.plantationplan', verbose_name='Plantation Plan'),
        ),
        migrations.AlterField(
            model_name='plantationevent',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productsubfamily', verbose_name='Culture (Subfamily)'),
        ),
    ]
