# Generated by Django 5.2.7 on 2026-06-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_plantationplan_production_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubfamily',
            name='lifecycle_presets',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Lifecycle Presets (Biological Coefficients)'),
        ),
        migrations.CreateModel(
            name='WarehouseSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Leitura')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidade (%)')),
                ('ethylene', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Etileno (ppm)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='dashboard.warehouse')),
            ],
            options={
                'db_table': 'warehouse_sensor_readings',
                'ordering': ['-date'],
                'unique_together': {('warehouse', 'date')},
            },
        ),
    ]
