# Generated by Django 5.2.7 on 2025-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_plantationevent_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricenergydata',
            name='main_usage',
            field=models.CharField(max_length=100, verbose_name='Main Usage'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='percent_grid',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Grid'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='percent_other_renewable',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Other Renewable'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='percent_photovoltaic',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Photovoltaic (Self)'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='total_consumption_kwh_year',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Consumption (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='application_mode',
            field=models.CharField(max_length=100, verbose_name='Application Mode'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='dose_tha_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose (t/ha/year)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='k_content_kgt',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='K Content (kg/t or %)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='n_content_kgt',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='N Content (kg/t or %)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='organic_fertilizer_type',
            field=models.CharField(max_length=100, verbose_name='Organic Fertilizer Type'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='origin',
            field=models.CharField(max_length=50, verbose_name='Origin (livestock, compost, etc.)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='p_content_kgt',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='P Content (kg/t or %)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='application_season',
            field=models.CharField(max_length=50, verbose_name='Application Season (month)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='commercial_product',
            field=models.CharField(max_length=100, verbose_name='Commercial Product'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='form_npk',
            field=models.CharField(max_length=50, verbose_name='Form (NPK, etc.)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='k2o_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='K2O Content (%)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='n_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='N Content (%)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='num_applications',
            field=models.IntegerField(verbose_name='No. of Applications'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='p2o5_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='P2O5 Content (%)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='total_dose_kg_ha_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Dose (kg/ha/year)'),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='annual_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Consumption'),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='fuel_type',
            field=models.CharField(max_length=100, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='main_usage_season',
            field=models.CharField(max_length=100, verbose_name='Main Usage Season'),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='estimated_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimated Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='extraction_method',
            field=models.CharField(max_length=100, verbose_name='Extraction Method'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='irrigation_system',
            field=models.CharField(max_length=100, verbose_name='Irrigation System'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='pumping_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pumping Height (m)'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='volume_m3_year',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (m3/year)'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='water_source',
            field=models.CharField(max_length=100, verbose_name='Water Source'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='hours_per_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hours/Year'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='machinery_type',
            field=models.CharField(max_length=100, verbose_name='Machinery Type'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='main_operation',
            field=models.CharField(max_length=100, verbose_name='Main Operation'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='power',
            field=models.CharField(max_length=50, verbose_name='Power (kW or CV)'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='active_substance',
            field=models.CharField(max_length=100, verbose_name='Active Substance'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='application_mode',
            field=models.CharField(max_length=100, verbose_name='Application Mode'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='commercial_product',
            field=models.CharField(max_length=100, verbose_name='Commercial Product'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='dose_per_application',
            field=models.CharField(max_length=50, verbose_name='Dose (kg or L/ha/application)'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='num_applications_year',
            field=models.IntegerField(verbose_name='No. Applications/Year'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='pest_type',
            field=models.CharField(max_length=100, verbose_name='Type (fungicide, insecticide, etc.)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='caco3_content',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CaCO3 Equivalent Content (%)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='commercial_product',
            field=models.CharField(max_length=100, verbose_name='Commercial Product'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='corrective_type',
            field=models.CharField(max_length=100, verbose_name='Type (limestone, dolomite, gypsum, etc.)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='dose_kg_ha_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose (kg/ha/year)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='frequency_years',
            field=models.IntegerField(verbose_name='Frequency (years)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
    ]
