# Generated by Django 5.2.7 on 2026-06-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_productsubfamily_lifecycle_presets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_location', models.CharField(max_length=255, verbose_name='Localização do Armazém')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Quantidade em Stock (Kg)')),
                ('avg_caliber', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Calibre Médio (mm)')),
                ('avg_soluble_solids', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Sólidos Solúveis Médios (Brix)')),
                ('avg_quality_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Score de Qualidade Médio')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consolidated_stock',
                'unique_together': {('owner', 'culture', 'warehouse_location')},
            },
        ),
    ]
