# Generated by Django 5.2.7 on 2026-07-03 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_consolidatedstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='producer_type',
            field=models.CharField(choices=[('manual', 'Manual/Tradicional'), ('instant', 'Compra Direta (Makro)'), ('contract', 'Contrato Futuro')], default='manual', max_length=20, verbose_name='Tipo de Produtor'),
        ),
        migrations.CreateModel(
            name='CultureShelfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_shelf_life_days', models.IntegerField(default=10, verbose_name='Tempo de Vida Padrão (Dias)')),
                ('subfamily', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_life', to='dashboard.productsubfamily', verbose_name='Cultura (Subfamília)')),
            ],
            options={
                'verbose_name': 'Validade de Cultura',
                'verbose_name_plural': 'Validades de Culturas',
                'db_table': 'culture_shelf_life',
            },
        ),
        migrations.CreateModel(
            name='SupplyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Contratada (Kg)')),
                ('delivery_date', models.DateField(verbose_name='Data de Entrega Planeada (Dia X)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('fulfilled', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado do Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Comprador (Retailer/Processor)')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Produtor Virtual (Tipo 3)')),
                ('subfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura (Subfamília)')),
            ],
            options={
                'verbose_name': 'Contrato de Fornecimento',
                'verbose_name_plural': 'Contratos de Fornecimento',
                'db_table': 'supply_contract',
            },
        ),
    ]
