# Generated by Django 5.2.7 on 2026-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_userprofile_producer_type_cultureshelflife_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date (Validade)'),
        ),
    ]
