# Generated by Django 5.2.7 on 2026-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_harvest_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycontract',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Entrega (Armazém)'),
        ),
    ]
