# Generated by Django 5.2.7 on 2026-07-07 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_supplycontract_warehouse_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Previsão')),
                ('predicted_quantity_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade Prevista (Kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Previsão de Procura',
                'verbose_name_plural': 'Previsões de Procura',
                'db_table': 'demand_forecast',
                'unique_together': {('owner', 'culture', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Venda')),
                ('sales_quantity_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vendas em Kg')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de Venda (€/Kg)')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sales', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Histórico de Vendas',
                'verbose_name_plural': 'Históricos de Vendas',
                'db_table': 'historical_sales_data',
                'unique_together': {('owner', 'culture', 'date')},
            },
        ),
    ]
