# Generated by Django 5.2.7 on 2026-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_demandforecast_historicalsalesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buyer_agent_active',
            field=models.BooleanField(default=False, verbose_name='Agente de Compras Ativo'),
        ),
    ]
