# Generated by Django 5.2.7 on 2026-07-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_userprofile_buyer_agent_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50, verbose_name='Tipo de Modelo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Ficheiro')),
                ('file_data', models.BinaryField(verbose_name='Dados do Ficheiro (Binário)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Cultura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Modelo de IA Treinado',
                'verbose_name_plural': 'Modelos de IA Treinados',
                'db_table': 'trained_model',
                'unique_together': {('owner', 'culture', 'model_type', 'file_name')},
            },
        ),
    ]
