# Generated by Django 5.2.7 on 2026-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_trainedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.CharField(choices=[('PT-NL', 'Norte Litoral (Muito húmido, temperaturas moderadas)'), ('PT-NI', 'Norte Interior (Invernos frios, verões quentes)'), ('PT-CL', 'Centro Litoral (Clima marítimo temperado)'), ('PT-CI', 'Centro Interior (Grande amplitude térmica)'), ('PT-LVT', 'Lisboa e Vale do Tejo (Mediterrânico moderado)'), ('PT-AL', 'Alentejo (Muito quente e seco no verão)'), ('PT-ALG', 'Algarve (Mediterrânico costeiro)'), ('PT-SM', 'Serra da Estrela e montanhas (Frio e neve no inverno)'), ('PT-MAD', 'Madeira (Subtropical oceânico)'), ('PT-ACO', 'Açores (Oceânico húmido)')], default='PT-LVT', max_length=10, verbose_name='Região Climática'),
        ),
    ]
