# Generated by Django 5.2.7 on 2026-08-03 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_warehouse_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Rota')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente (Criada Automática)'), ('ACCEPTED', 'Aceite pelo Transportador'), ('PLANNED', 'Planeada'), ('IN_TRANSIT', 'Em Trânsito'), ('DELIVERED', 'Entregue')], default='PENDING', max_length=20, verbose_name='Estado da Rota')),
                ('optimized_path', models.TextField(blank=True, null=True, verbose_name='Caminho Otimizado (Pontos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporter', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Transporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Transportador')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.route', verbose_name='Rota'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('brand_model', models.CharField(max_length=100, verbose_name='Marca/Modelo')),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade (Kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'Transporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle', verbose_name='Veículo'),
        ),
    ]
