# Generated by Django 5.2.7 on 2026-08-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_warehouse_latitude_warehouse_longitude_route_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProcessorAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.ForeignKey(limit_choices_to={'groups__name': 'Processor'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_associations', to=settings.AUTH_USER_MODEL, verbose_name='Processador')),
                ('retailer', models.ForeignKey(limit_choices_to={'groups__name': 'Retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='processor_associations', to=settings.AUTH_USER_MODEL, verbose_name='Retalhista/Loja')),
            ],
            options={
                'verbose_name': 'Associação de Loja',
                'verbose_name_plural': 'Associações de Lojas',
                'db_table': 'store_processor_associations',
                'unique_together': {('processor', 'retailer')},
            },
        ),
    ]
