# Generated by Django 6.1.1 on 2026-09-10 09:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_storeprocessorassociation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultureshelflife',
            options={'verbose_name': 'Culture Shelf Life', 'verbose_name_plural': 'Culture Shelf Lives'},
        ),
        migrations.AlterModelOptions(
            name='demandforecast',
            options={'verbose_name': 'Demand Forecast', 'verbose_name_plural': 'Demand Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='historicalsalesdata',
            options={'verbose_name': 'Sales History', 'verbose_name_plural': 'Sales Histories'},
        ),
        migrations.AlterModelOptions(
            name='storeprocessorassociation',
            options={'verbose_name': 'Store Association', 'verbose_name_plural': 'Store Associations'},
        ),
        migrations.AlterModelOptions(
            name='supplycontract',
            options={'verbose_name': 'Supply Contract', 'verbose_name_plural': 'Supply Contracts'},
        ),
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'verbose_name': 'Trained AI Model', 'verbose_name_plural': 'Trained AI Models'},
        ),
        migrations.AlterField(
            model_name='consolidatedstock',
            name='avg_caliber',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Average Caliber (mm)'),
        ),
        migrations.AlterField(
            model_name='consolidatedstock',
            name='avg_quality_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Average Quality Score'),
        ),
        migrations.AlterField(
            model_name='consolidatedstock',
            name='avg_soluble_solids',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Average Soluble Solids (Brix)'),
        ),
        migrations.AlterField(
            model_name='consolidatedstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Stock Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='consolidatedstock',
            name='warehouse_location',
            field=models.CharField(max_length=255, verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='cultureshelflife',
            name='default_shelf_life_days',
            field=models.IntegerField(default=10, verbose_name='Default Shelf Life (Days)'),
        ),
        migrations.AlterField(
            model_name='cultureshelflife',
            name='subfamily',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_life', to='dashboard.productsubfamily', verbose_name='Culture (Subfamily)'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='date',
            field=models.DateField(verbose_name='Forecast Date'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='predicted_quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Predicted Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='percent_grid',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Grid'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='percent_other_renewable',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Other Renewable'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='percent_photovoltaic',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Photovoltaic (Self)'),
        ),
        migrations.AlterField(
            model_name='electricenergydata',
            name='total_consumption_kwh_year',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Consumption (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='dose_tha_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dose (t/ha/year)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='k_content_kgt',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='K Content (kg/t or %)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='n_content_kgt',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N Content (kg/t or %)'),
        ),
        migrations.AlterField(
            model_name='fertilizerorganicdata',
            name='p_content_kgt',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='P Content (kg/t or %)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='k2o_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'K2O Content cannot be negative.')], verbose_name='K2O Content (%)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='n_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'N Content cannot be negative.')], verbose_name='N Content (%)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='num_applications',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Number of applications cannot be negative.')], verbose_name='No. of Applications'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='p2o5_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'P2O5 Content cannot be negative.')], verbose_name='P2O5 Content (%)'),
        ),
        migrations.AlterField(
            model_name='fertilizersyntheticdata',
            name='total_dose_kg_ha_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, 'Total Dose cannot be negative.')], verbose_name='Total Dose (kg/ha/year)'),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='annual_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Consumption'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date (Shelf Life)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='plantation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_records', to='dashboard.plantationplan', verbose_name='Plantation Plan'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productsubfamily', verbose_name='Culture (Subfamily)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.warehouse', verbose_name='Stored In Warehouse'),
        ),
        migrations.AlterField(
            model_name='historicalsalesdata',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalsalesdata',
            name='date',
            field=models.DateField(verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='historicalsalesdata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sales', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalsalesdata',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Selling Price (€/Kg)'),
        ),
        migrations.AlterField(
            model_name='historicalsalesdata',
            name='sales_quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sales in Kg'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='estimated_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Estimated Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='pumping_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pumping Height (m)'),
        ),
        migrations.AlterField(
            model_name='irrigationwaterdata',
            name='volume_m3_year',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume (m3/year)'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='hours_per_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, 'Hours/Year cannot be negative.')], verbose_name='Hours/Year'),
        ),
        migrations.AlterField(
            model_name='machinerydata',
            name='power',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_power', message="Power must be a positive number followed by 'kW' or 'CV' (e.g., '15.5kW', '100 CV').", regex='^\\d+(\\.\\d+)?\\s*(kW|CV)$')], verbose_name='Power (kW or CV)'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Date'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='actual_pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Pickup Date'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='harvest_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders', to='dashboard.harvest', verbose_name='Origin (Harvest)'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed?'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'Purchase Request'), ('SELL', 'Export Offer')], max_length=10, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('Plastic', 'Plastic'), ('Cardboard', 'Cardboard'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Packaging Type'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='planned_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned Delivery Date'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='planned_pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned Pickup Date'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='preservation_treatment',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural Treatment'), ('Conventional', 'Conventional/Chemical'), ('None', 'None')], max_length=50, null=True, verbose_name='Preservation Treatment'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Requester Profile'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved/Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='transport_sensor_data',
            field=models.TextField(blank=True, null=True, verbose_name='Sensor Data (JSON)'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='transport_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Job Accepted'), ('PLANNED', 'Planned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20, verbose_name='Transport Status'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='warehouse_location',
            field=models.CharField(max_length=255, verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='pestcontroldata',
            name='num_applications_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Number of applications cannot be negative.')], verbose_name='No. Applications/Year'),
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='irrigation_system',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip Irrigation'), ('Sprinkler', 'Sprinkler')], max_length=50, null=True, verbose_name='Irrigation System Type'),
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='plantation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='dashboard.plantationplan', verbose_name='Plantation Plan'),
        ),
        migrations.AlterField(
            model_name='plantationcrop',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Culture (Subfamily)'),
        ),
        migrations.AlterField(
            model_name='plantationevent',
            name='event_type',
            field=models.CharField(choices=[('Fert_Min', 'Fertilizers (synthetic minerals)'), ('Fert_Org', 'Fertilizers (organic)'), ('Soil_Corr', 'Soil Correctives'), ('Pest', 'Phytopharmaceutical Products'), ('Machine_Hrs', 'Machinery Hours'), ('Fuel', 'Fuels'), ('Electric', 'Electric Energy'), ('Water', 'Irrigation Water')], max_length=50, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (m²)'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='chemical_use',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name='Chemical Use'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='conduct_system',
            field=models.CharField(blank=True, choices=[('T-bar', 'T-bar'), ('Pergola', 'Pergola')], max_length=50, null=True, verbose_name='Conduct System'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='organic_matter_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Soil Organic Matter (%)'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='ph_soil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Soil pH'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='plantation_date',
            field=models.DateField(verbose_name='Plantation Date'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='plantation_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plantation Name'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='production_type',
            field=models.CharField(choices=[('conventional', 'Conventional'), ('integrated', 'Integrated Production'), ('organic', 'Organic'), ('regenerative', 'Regenerative'), ('precision', 'Precision'), ('agroforestry', 'Agroforestry')], max_length=20, verbose_name='Agriculture Type'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='quantity_of_trees',
            field=models.IntegerField(verbose_name='Number of Trees'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Clay', 'Clay'), ('Sand', 'Sand'), ('Loam', 'Loam')], max_length=50, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='total_area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total orchard area (m²)'),
        ),
        migrations.AlterField(
            model_name='plantationplan',
            name='water_regime',
            field=models.CharField(blank=True, choices=[('Total', 'Total Irrigation'), ('Supp', 'Supplemental'), ('Dry', 'Rainfed')], max_length=20, null=True, verbose_name='Water Regime'),
        ),
        migrations.AlterField(
            model_name='plantationsoilvalue',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Recorded Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling Price (€)'),
        ),
        migrations.AlterField(
            model_name='productsubfamily',
            name='fruit_type',
            field=models.CharField(choices=[('Kiwi', 'Kiwi'), ('Apple', 'Apple')], max_length=50, verbose_name='Fruit Type'),
        ),
        migrations.AlterField(
            model_name='productsubfamily',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subfamily'),
        ),
        migrations.AlterField(
            model_name='route',
            name='optimized_path',
            field=models.TextField(blank=True, null=True, verbose_name='Optimized Path (Points)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Route Date'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Auto-Created)'), ('ACCEPTED', 'Accepted by Transporter'), ('PLANNED', 'Planned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20, verbose_name='Route Status'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Transporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Transporter'),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Sensor Brand'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Light', 'Light'), ('Gas', 'Gas/CO2')], max_length=50, verbose_name='Sensor Type'),
        ),
        migrations.AlterField(
            model_name='soilcharacteristic',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='soilcharacteristic',
            name='sub_category',
            field=models.CharField(max_length=100, verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='soilcharacteristic',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Measurement Unit'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='caco3_content',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='CaCO3 Equivalent Content (%)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='dose_kg_ha_year',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dose (kg/ha/year)'),
        ),
        migrations.AlterField(
            model_name='soilcorrectivedata',
            name='frequency_years',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frequency (years)'),
        ),
        migrations.AlterField(
            model_name='storeprocessorassociation',
            name='processor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Processor'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_associations', to=settings.AUTH_USER_MODEL, verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='storeprocessorassociation',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='processor_associations', to=settings.AUTH_USER_MODEL, verbose_name='Retailer/Store'),
        ),
        migrations.AlterField(
            model_name='storeprocessorassociation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Buyer (Retailer/Processor)'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='delivery_date',
            field=models.DateField(verbose_name='Planned Delivery Date (Day X)'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Virtual Producer (Type 3)'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Contracted Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Contract Status'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Culture (Subfamily)'),
        ),
        migrations.AlterField(
            model_name='supplycontract',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Location (Warehouse)'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productsubfamily', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='file_data',
            field=models.BinaryField(verbose_name='File Data (Binary)'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_type',
            field=models.CharField(max_length=50, verbose_name='Model Type'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='buyer_agent_active',
            field=models.BooleanField(default=False, verbose_name='Shopping Agent Active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='producer_type',
            field=models.CharField(choices=[('manual', 'Manual/Traditional'), ('instant', 'Direct Purchase (Makro)'), ('contract', 'Future Contract')], default='manual', max_length=20, verbose_name='Producer Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand_model',
            field=models.CharField(max_length=100, verbose_name='Brand/Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacity (Kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Transporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacity (m² or Kg)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='control_type',
            field=models.CharField(choices=[('Controlled', 'Controlled'), ('Non-Controlled', 'Uncontrolled')], max_length=20, verbose_name='Warehouse Type'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Producer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner/Profile'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='region',
            field=models.CharField(choices=[('PT-NL', 'PT-NL: North Coast (Very humid, moderate temperatures)'), ('PT-NI', 'PT-NI: Inland North (Cold winters, hot summers)'), ('PT-CL', 'PT-CL: Center Coast (Temperate maritime climate)'), ('PT-CI', 'PT-CI: Center Inland (Large thermal amplitude)'), ('PT-LVT', 'PT-LVT: Lisbon and Tagus Valley (Moderate Mediterranean)'), ('PT-AL', 'PT-AL: Alentejo (Very hot and dry in summer)'), ('PT-ALG', 'PT-ALG: Algarve (Coastal Mediterranean)'), ('PT-SM', 'PT-SM: Serra da Estrela and mountains (Cold and snowy in winter)'), ('PT-MAD', 'PT-MAD: Madeira (Oceanic subtropical)'), ('PT-ACO', 'PT-ACO: Azores (Oceanic humid)')], default='PT-LVT', max_length=10, verbose_name='Climate Region'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='dashboard.sensor', verbose_name='Installed Sensors'),
        ),
        migrations.AlterField(
            model_name='warehousesensorreading',
            name='date',
            field=models.DateField(verbose_name='Reading Date'),
        ),
        migrations.AlterField(
            model_name='warehousesensorreading',
            name='ethylene',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Ethylene (ppm)'),
        ),
        migrations.AlterField(
            model_name='warehousesensorreading',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='warehousesensorreading',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature (°C)'),
        ),
    ]
