# Generated by Django 5.2.7 on 2026-09-09 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_storeprocessorassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data Real de Entrega'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open (Aberto)'), ('APPROVED', 'Approved/Fulfilled (Aprovado)')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='transport_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Pendente)'), ('ACCEPTED', 'Job Accepted (Aceite)'), ('PLANNED', 'Planned (Planeado)'), ('IN_TRANSIT', 'In Transit (Em Trânsito)'), ('DELIVERED', 'Delivered (Entregue)')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado do Transporte'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da Rota'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente (Criada Automática)'), ('ACCEPTED', 'Aceite pelo Transportador'), ('PLANNED', 'Planeada'), ('IN_TRANSIT', 'Em Trânsito'), ('DELIVERED', 'Entregue')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado da Rota'),
        ),
    ]
