# Generated by Django 5.2.7 on 2026-09-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_marketplaceorder_actual_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('VAN', 'Carrinha Ligeira (3.5t)'), ('RIGID_TRUCK', 'Camião Ligeiro (12t)'), ('HEAVY_TIR', 'Camião TIR (40t)')], default='RIGID_TRUCK', max_length=20, verbose_name='Tipo de Veículo'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='max_vehicle_access',
            field=models.CharField(choices=[('VAN', 'Apenas Carrinha Ligeira (<= 3.5t)'), ('RIGID_TRUCK', 'Até Camião Ligeiro (<= 12t)'), ('HEAVY_TIR', 'Todos / Camião TIR (<= 40t)')], default='HEAVY_TIR', max_length=20, verbose_name='Acesso Máximo de Veículo'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='storage_unit',
            field=models.CharField(choices=[('CRATES', 'Grades (20 Kg / Caixa)'), ('PALLETS', 'Paletes (800 Kg / Euro-Palete)')], default='PALLETS', max_length=20, verbose_name='Acondicionamento de Stock'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono/Perfil'),
        ),
    ]
