# Generated by Django 6.1.1 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_cultureshelflife_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationplan',
            name='plantation_name',
            field=models.CharField(max_length=100, verbose_name='Plantation Name'),
        ),
    ]
