# Generated by Django 5.2.7 on 2026-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_vehicle_vehicle_type_warehouse_max_vehicle_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidade (Kg)'),
        ),
    ]
