# Generated by Django 6.1.1 on 2026-09-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_plantationplan_plantation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('NEGOTIATING', 'Negotiating'), ('APPROVED', 'Approved/Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proposed Price (€/Kg)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='dashboard.marketplaceorder')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_negotiations',
                'ordering': ['-created_at'],
            },
        ),
    ]
