# Generated by Django 5.2.7 on 2026-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_vehicle_capacity_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='fixed_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, default=90.0, max_digits=5, null=True, verbose_name='Humidade Fixa (%)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fixed_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.0, max_digits=5, null=True, verbose_name='Temperatura Fixa (°C)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='json_fallback_mode',
            field=models.CharField(choices=[('NONE', 'Nenhum / Sem Fallback'), ('FIXED', 'Valores Fixos'), ('IPMA', 'IPMA (Estação Regional)')], default='FIXED', max_length=20, verbose_name='Modo de Preenchimento de Falhas (Fallback)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='meteo_source',
            field=models.CharField(choices=[('FIXED', 'Valores Fixos'), ('IPMA', 'IPMA (Estação Regional)'), ('JSON', 'Ficheiro JSON de Sensores')], default='FIXED', max_length=20, verbose_name='Fonte Meteorológica / Sensores'),
        ),
    ]
