# Generated by Django 5.2.7 on 2026-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_warehouse_fixed_humidity_warehouse_fixed_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesensorreading',
            name='ethylene',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Etileno (ppm)'),
        ),
    ]
