# Generated by Django 5.2.7 on 2026-09-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_warehousesensorreading_ethylene'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='acidity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Acidez (g/L / %)'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='firmness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Firmeza (N / kg/cm²)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='avg_quality_score',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Score de Qualidade (Calculado)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='caliber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calibre (mm)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='soluble_solids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor de Açúcar / Brix (°Bx)'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='utilized_quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Waste (Kg)'),
        ),
    ]
