# =============================================================================
# BIOLOGICAL FRUIT PRESETS & DECAY PARAMETERS
# =============================================================================
# Supports two complementary decay formulations:
# 1) PRESETS_ACADEMIC: Models with Endogenous Ethylene synthesis dynamics (Prof. Luís Paulo)
# 2) PRESETS_SOFIA: Multi-attribute decay with Acidity, VPD, and Stakeholder Profiles (Sofia Machado)
# =============================================================================

PRESETS_ACADEMIC = {
    "kiwi_hayward": {
        "label": "Kiwi (Hayward)",
        "Tref_C": 5.0,
        "Ea_J": 60000,
        "k_firm_ref": 0.06,
        "alpha_E": 1.8,
        "beta_RH": 1.2,
        "RH_ref": 90,
        "brix_min": 11,
        "brix_max": 17,
        "brix_g": 0.35,
        "brix_0_default": 11.0,
        "qual_brix_target": 15,
        "E0_int": 0.02,
        "Eref_prod": 0.12,
        "E_t0": 10,
        "E_g": 0.9,
        "E_auto": 0.35,
        "E_decay": 0.7,
        "Ea_E_J": 52000,
        "E_ext_shift": 2.0,
        "firmness_min": 3,
        "firmness_0_default": 45,
        "qual_firmness_threshold": 8,
    },
    "kiwi_baby": {
        "label": "Kiwi (Baby/Berry)",
        "Tref_C": 4.0,
        "Ea_J": 58000,
        "k_firm_ref": 0.14,
        "alpha_E": 3.2,
        "beta_RH": 2.0,
        "RH_ref": 95,
        "brix_min": 13,
        "brix_max": 20,
        "brix_g": 0.5,
        "brix_0_default": 14.5,
        "qual_brix_target": 17,
        "E0_int": 0.03,
        "Eref_prod": 0.22,
        "E_t0": 5,
        "E_g": 1.2,
        "E_auto": 0.55,
        "E_decay": 0.75,
        "Ea_E_J": 52000,
        "E_ext_shift": 2.6,
        "firmness_min": 2,
        "firmness_0_default": 28,
        "qual_firmness_threshold": 6,
    },
    "apple_golden": {
        "label": "Apple (Golden)",
        "Tref_C": 5.0,
        "Ea_J": 50000,
        "k_firm_ref": 0.025,
        "alpha_E": 0.8,
        "beta_RH": 0.8,
        "RH_ref": 90,
        "brix_min": 11.5,
        "brix_max": 15.5,
        "brix_g": 0.18,
        "brix_0_default": 12.0,
        "qual_brix_target": 13.5,
        "E0_int": 0.01,
        "Eref_prod": 0.1,
        "E_t0": 18,
        "E_g": 0.6,
        "E_auto": 0.35,
        "E_decay": 0.55,
        "Ea_E_J": 52000,
        "E_ext_shift": 1.8,
        "firmness_min": 12,
        "firmness_0_default": 72,
        "qual_firmness_threshold": 35,
    },
    "apple_reineta": {
        "label": "Apple (Reineta)",
        "Tref_C": 5.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.035,
        "alpha_E": 1.1,
        "beta_RH": 1.0,
        "RH_ref": 90,
        "brix_min": 11.0,
        "brix_max": 14.0,
        "brix_g": 0.16,
        "brix_0_default": 11.5,
        "qual_brix_target": 12.5,
        "E0_int": 0.01,
        "Eref_prod": 0.13,
        "E_t0": 14,
        "E_g": 0.7,
        "E_auto": 0.4,
        "E_decay": 0.6,
        "Ea_E_J": 52000,
        "E_ext_shift": 2.0,
        "firmness_min": 10,
        "firmness_0_default": 65,
        "qual_firmness_threshold": 30,
    },
    "apple_gala": {
        "label": "Apple (Gala)",
        "Tref_C": 5.0,
        "Ea_J": 48000,
        "k_firm_ref": 0.04,
        "alpha_E": 1.3,
        "beta_RH": 0.9,
        "RH_ref": 90,
        "brix_min": 12.5,
        "brix_max": 17.0,
        "brix_g": 0.25,
        "brix_0_default": 13.0,
        "qual_brix_target": 14.5,
        "E0_int": 0.015,
        "Eref_prod": 0.18,
        "E_t0": 10,
        "E_g": 0.9,
        "E_auto": 0.5,
        "E_decay": 0.65,
        "Ea_E_J": 52000,
        "E_ext_shift": 2.2,
        "firmness_min": 9,
        "firmness_0_default": 60,
        "qual_firmness_threshold": 28,
    },
    "apple_fuji": {
        "label": "Apple (Fuji)",
        "Tref_C": 5.0,
        "Ea_J": 47000,
        "k_firm_ref": 0.018,
        "alpha_E": 0.6,
        "beta_RH": 0.7,
        "RH_ref": 90,
        "brix_min": 13.0,
        "brix_max": 19.0,
        "brix_g": 0.15,
        "brix_0_default": 14.0,
        "qual_brix_target": 16.0,
        "E0_int": 0.008,
        "Eref_prod": 0.06,
        "E_t0": 25,
        "E_g": 0.5,
        "E_auto": 0.25,
        "E_decay": 0.45,
        "Ea_E_J": 52000,
        "E_ext_shift": 1.4,
        "firmness_min": 15,
        "firmness_0_default": 80,
        "qual_firmness_threshold": 40,
    },
    "orange": {
        "label": "Orange",
        "Tref_C": 5.0,
        "Ea_J": 42000,
        "k_firm_ref": 0.01,
        "alpha_E": 0.15,
        "beta_RH": 0.35,
        "RH_ref": 90,
        "brix_min": 10.5,
        "brix_max": 13.5,
        "brix_g": 0.1,
        "brix_0_default": 11.5,
        "qual_brix_target": 12.2,
        "E0_int": 0.002,
        "Eref_prod": 0.01,
        "E_t0": 999,
        "E_g": 0.2,
        "E_auto": 0.0,
        "E_decay": 0.8,
        "Ea_E_J": 40000,
        "E_ext_shift": 0.5,
        "firmness_min": 35,
        "firmness_0_default": 55,
        "qual_firmness_threshold": 42,
    },
    "banana": {
        "label": "Banana",
        "Tref_C": 14.0,
        "Ea_J": 65000,
        "k_firm_ref": 0.09,
        "alpha_E": 2.2,
        "beta_RH": 1.0,
        "RH_ref": 90,
        "brix_min": 12.0,
        "brix_max": 22.0,
        "brix_g": 0.45,
        "brix_0_default": 12.5,
        "qual_brix_target": 19,
        "E0_int": 0.02,
        "Eref_prod": 0.35,
        "E_t0": 4,
        "E_g": 1.4,
        "E_auto": 0.7,
        "E_decay": 0.9,
        "Ea_E_J": 60000,
        "E_ext_shift": 3.0,
        "firmness_min": 5,
        "firmness_0_default": 80,
        "qual_firmness_threshold": 15,
    },
    "blueberry": {
        "label": "Blueberry",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.03,
        "alpha_E": 0.1,
        "beta_RH": 1.6,
        "RH_ref": 95,
        "brix_min": 10.0,
        "brix_max": 14.0,
        "brix_g": 0.2,
        "brix_0_default": 11.5,
        "qual_brix_target": 12.5,
        "E0_int": 0.002,
        "Eref_prod": 0.01,
        "E_t0": 999,
        "E_g": 0.2,
        "E_auto": 0.0,
        "E_decay": 0.9,
        "Ea_E_J": 42000,
        "E_ext_shift": 0.4,
        "firmness_min": 6,
        "firmness_0_default": 30,
        "qual_firmness_threshold": 12,
    },
    "raspberry": {
        "label": "Raspberry",
        "Tref_C": 2.0,
        "Ea_J": 56000,
        "k_firm_ref": 0.06,
        "alpha_E": 0.12,
        "beta_RH": 2.2,
        "RH_ref": 95,
        "brix_min": 7.0,
        "brix_max": 12.0,
        "brix_g": 0.22,
        "brix_0_default": 9.5,
        "qual_brix_target": 10.0,
        "E0_int": 0.002,
        "Eref_prod": 0.01,
        "E_t0": 999,
        "E_g": 0.2,
        "E_auto": 0.0,
        "E_decay": 0.9,
        "Ea_E_J": 42000,
        "E_ext_shift": 0.4,
        "firmness_min": 2.5,
        "firmness_0_default": 18,
        "qual_firmness_threshold": 6,
    },
    "pear": {
        "label": "Pear",
        "Tref_C": 2.0,
        "Ea_J": 54000,
        "k_firm_ref": 0.05,
        "alpha_E": 1.6,
        "beta_RH": 1.2,
        "RH_ref": 92,
        "brix_min": 10.5,
        "brix_max": 16.5,
        "brix_g": 0.28,
        "brix_0_default": 11.5,
        "qual_brix_target": 14.0,
        "E0_int": 0.01,
        "Eref_prod": 0.22,
        "E_t0": 10,
        "E_g": 1.0,
        "E_auto": 0.6,
        "E_decay": 0.75,
        "Ea_E_J": 56000,
        "E_ext_shift": 2.3,
        "firmness_min": 4,
        "firmness_0_default": 55,
        "qual_firmness_threshold": 10,
    },
    "plum": {
        "label": "Plum",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.06,
        "alpha_E": 1.0,
        "beta_RH": 1.0,
        "RH_ref": 92,
        "brix_min": 11.0,
        "brix_max": 20.0,
        "brix_g": 0.3,
        "brix_0_default": 12.5,
        "qual_brix_target": 16.5,
        "E0_int": 0.01,
        "Eref_prod": 0.14,
        "E_t0": 8,
        "E_g": 0.8,
        "E_auto": 0.45,
        "E_decay": 0.7,
        "Ea_E_J": 54000,
        "E_ext_shift": 2.0,
        "firmness_min": 3,
        "firmness_0_default": 40,
        "qual_firmness_threshold": 8,
    },
    "peach": {
        "label": "Peach",
        "Tref_C": 2.0,
        "Ea_J": 56000,
        "k_firm_ref": 0.08,
        "alpha_E": 1.4,
        "beta_RH": 1.1,
        "RH_ref": 92,
        "brix_min": 9.5,
        "brix_max": 18.0,
        "brix_g": 0.35,
        "brix_0_default": 11.0,
        "qual_brix_target": 15.0,
        "E0_int": 0.012,
        "Eref_prod": 0.22,
        "E_t0": 6,
        "E_g": 1.0,
        "E_auto": 0.55,
        "E_decay": 0.8,
        "Ea_E_J": 56000,
        "E_ext_shift": 2.4,
        "firmness_min": 2,
        "firmness_0_default": 35,
        "qual_firmness_threshold": 6,
    },
    "cherry": {
        "label": "Cherry",
        "Tref_C": 2.0,
        "Ea_J": 48000,
        "k_firm_ref": 0.045,
        "alpha_E": 0.05,
        "beta_RH": 1.6,
        "RH_ref": 95,
        "brix_min": 14.0,
        "brix_max": 20.0,
        "brix_g": 0.08,
        "brix_0_default": 16.0,
        "qual_brix_target": 18.0,
        "E0_int": 0.002,
        "Eref_prod": 0.01,
        "E_t0": 999,
        "E_g": 0.2,
        "E_auto": 0.0,
        "E_decay": 0.9,
        "Ea_E_J": 42000,
        "E_ext_shift": 0.4,
        "firmness_min": 4,
        "firmness_0_default": 28,
        "qual_firmness_threshold": 10,
    },
    "strawberry": {
        "label": "Strawberry",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.12,
        "alpha_E": 0.05,
        "beta_RH": 2.4,
        "RH_ref": 95,
        "brix_min": 6.0,
        "brix_max": 10.5,
        "brix_g": 0.12,
        "brix_0_default": 7.5,
        "qual_brix_target": 9.0,
        "E0_int": 0.002,
        "Eref_prod": 0.01,
        "E_t0": 999,
        "E_g": 0.2,
        "E_auto": 0.0,
        "E_decay": 0.9,
        "Ea_E_J": 42000,
        "E_ext_shift": 0.4,
        "firmness_min": 1.5,
        "firmness_0_default": 12,
        "qual_firmness_threshold": 4.5,
    },
    "grape": {
        "label": "Grape",
        "Tref_C": 2.0,
        "Ea_J": 45000,
        "k_firm_ref": 0.02,
        "alpha_E": 0.05,
        "beta_RH": 1.8,
        "RH_ref": 92,
        "brix_min": 14.0,
        "brix_max": 22.0,
        "brix_g": 0.05,
        "brix_0_default": 16.0,
        "qual_brix_target": 18.0,
        "E0_int": 0.002,
        "Eref_prod": 0.01,
        "E_t0": 999,
        "E_g": 0.2,
        "E_auto": 0.0,
        "E_decay": 0.9,
        "Ea_E_J": 42000,
        "E_ext_shift": 0.4,
        "firmness_min": 3,
        "firmness_0_default": 20,
        "qual_firmness_threshold": 7,
    },
    "fig": {
        "label": "Fig",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.11,
        "alpha_E": 0.2,
        "beta_RH": 1.8,
        "RH_ref": 95,
        "brix_min": 14.0,
        "brix_max": 26.0,
        "brix_g": 0.18,
        "brix_0_default": 16.0,
        "qual_brix_target": 20.0,
        "E0_int": 0.005,
        "Eref_prod": 0.05,
        "E_t0": 12,
        "E_g": 0.5,
        "E_auto": 0.15,
        "E_decay": 0.7,
        "Ea_E_J": 52000,
        "E_ext_shift": 1.0,
        "firmness_min": 1.2,
        "firmness_0_default": 10,
        "qual_firmness_threshold": 3.5,
    },
    "melon": {
        "label": "Melon",
        "Tref_C": 7.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.06,
        "alpha_E": 0.9,
        "beta_RH": 0.9,
        "RH_ref": 90,
        "brix_min": 9.0,
        "brix_max": 16.0,
        "brix_g": 0.22,
        "brix_0_default": 10.5,
        "qual_brix_target": 13.5,
        "E0_int": 0.01,
        "Eref_prod": 0.1,
        "E_t0": 10,
        "E_g": 0.7,
        "E_auto": 0.35,
        "E_decay": 0.7,
        "Ea_E_J": 52000,
        "E_ext_shift": 1.8,
        "firmness_min": 2.0,
        "firmness_0_default": 25,
        "qual_firmness_threshold": 6.0,
    },
}

PRESETS_SOFIA = {
    "kiwi_hayward": {
        "label": "Kiwi (Hayward)",
        "Tref_C": 5.0,
        "Ea_J": 60000,
        "k_firm_ref": 0.06,
        "beta_RH": 1.2,
        "RH_ref": 90,
        "brix_min": 11,
        "brix_max": 17,
        "brix_g": 0.35,
        "brix_0_default": 11.0,
        "qual_brix_target": 15,
        "SL_ref": 30,
        "firmness_min": 2,
        "firmness_0_default": 18,
        "qual_firmness_threshold": 5,
        "acidity_0_default": 1.5,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "kiwi_baby": {
        "label": "Kiwi (Baby/Berry)",
        "Tref_C": 4.0,
        "Ea_J": 58000,
        "k_firm_ref": 0.14,
        "beta_RH": 2.0,
        "RH_ref": 95,
        "brix_min": 8.0,
        "brix_max": 18.0,
        "brix_g": 0.5,
        "brix_0_default": 8.0,
        "qual_brix_target": 17.0,
        "SL_ref": 45,
        "firmness_min": 1.5,
        "firmness_0_default": 40,
        "qual_firmness_threshold": 6.0,
        "acidity_0_default": 1.1,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "apple_fuji": {
        "label": "Apple (Fuji)",
        "Tref_C": 5.0,
        "Ea_J": 47000,
        "k_firm_ref": 0.018,
        "beta_RH": 0.7,
        "RH_ref": 90,
        "brix_min": 13.0,
        "brix_max": 17.0,
        "brix_g": 0.15,
        "brix_0_default": 13.0,
        "qual_brix_target": 16.0,
        "SL_ref": 180,
        "firmness_min": 25.0,
        "firmness_0_default": 85,
        "qual_firmness_threshold": 45.0,
        "acidity_0_default": 0.4,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "apple_golden": {
        "label": "Apple (Golden)",
        "Tref_C": 5.0,
        "Ea_J": 50000,
        "k_firm_ref": 0.025,
        "beta_RH": 0.8,
        "RH_ref": 90,
        "brix_min": 11.0,
        "brix_max": 14.5,
        "brix_g": 0.18,
        "brix_0_default": 11.0,
        "qual_brix_target": 13.5,
        "SL_ref": 120,
        "firmness_min": 20.0,
        "firmness_0_default": 70,
        "qual_firmness_threshold": 40.0,
        "acidity_0_default": 0.5,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "apple_gala": {
        "label": "Apple (Gala)",
        "Tref_C": 5.0,
        "Ea_J": 48000,
        "k_firm_ref": 0.04,
        "beta_RH": 0.9,
        "RH_ref": 90,
        "brix_min": 12.0,
        "brix_max": 15.0,
        "brix_g": 0.2,
        "brix_0_default": 12.0,
        "qual_brix_target": 14.5,
        "SL_ref": 90,
        "firmness_min": 16.0,
        "firmness_0_default": 70,
        "qual_firmness_threshold": 30.0,
        "acidity_0_default": 0.4,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "apple_reineta": {
        "label": "Apple (Reineta)",
        "Tref_C": 5.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.035,
        "beta_RH": 1.0,
        "RH_ref": 90,
        "brix_min": 10.5,
        "brix_max": 13.5,
        "brix_g": 0.16,
        "brix_0_default": 10.5,
        "qual_brix_target": 12.5,
        "SL_ref": 90,
        "firmness_min": 18.0,
        "firmness_0_default": 65,
        "qual_firmness_threshold": 35.0,
        "acidity_0_default": 0.8,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "strawberry": {
        "label": "Strawberry",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.12,
        "beta_RH": 2.4,
        "RH_ref": 95,
        "brix_min": 7.5,
        "brix_max": 8.0,
        "brix_g": 0.01,
        "brix_0_default": 7.5,
        "qual_brix_target": 7.5,
        "SL_ref": 7,
        "firmness_min": 1.0,
        "firmness_0_default": 5,
        "qual_firmness_threshold": 2.0,
        "acidity_0_default": 0.8,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "raspberry": {
        "label": "Raspberry",
        "Tref_C": 2.0,
        "Ea_J": 56000,
        "k_firm_ref": 0.06,
        "beta_RH": 2.2,
        "RH_ref": 95,
        "brix_min": 9.5,
        "brix_max": 10.0,
        "brix_g": 0.01,
        "brix_0_default": 9.5,
        "qual_brix_target": 9.5,
        "SL_ref": 7,
        "firmness_min": 1.5,
        "firmness_0_default": 6,
        "qual_firmness_threshold": 2.5,
        "acidity_0_default": 1.2,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "blueberry": {
        "label": "Blueberry",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.03,
        "beta_RH": 1.6,
        "RH_ref": 95,
        "brix_min": 11.5,
        "brix_max": 12.0,
        "brix_g": 0.01,
        "brix_0_default": 11.5,
        "qual_brix_target": 11.5,
        "SL_ref": 21,
        "firmness_min": 3.0,
        "firmness_0_default": 10,
        "qual_firmness_threshold": 4.0,
        "acidity_0_default": 0.6,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "cherry": {
        "label": "Cherry",
        "Tref_C": 2.0,
        "Ea_J": 48000,
        "k_firm_ref": 0.045,
        "beta_RH": 1.6,
        "RH_ref": 95,
        "brix_min": 16.0,
        "brix_max": 16.5,
        "brix_g": 0.01,
        "brix_0_default": 16.0,
        "qual_brix_target": 16.0,
        "SL_ref": 21,
        "firmness_min": 8.0,
        "firmness_0_default": 15,
        "qual_firmness_threshold": 10.0,
        "acidity_0_default": 0.5,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "peach": {
        "label": "Peach",
        "Tref_C": 2.0,
        "Ea_J": 56000,
        "k_firm_ref": 0.08,
        "beta_RH": 1.1,
        "RH_ref": 92,
        "brix_min": 10.0,
        "brix_max": 14.0,
        "brix_g": 0.2,
        "brix_0_default": 10.0,
        "qual_brix_target": 13.0,
        "SL_ref": 14,
        "firmness_min": 4.0,
        "firmness_0_default": 40,
        "qual_firmness_threshold": 8.0,
        "acidity_0_default": 0.6,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "plum": {
        "label": "Plum",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.06,
        "beta_RH": 1.0,
        "RH_ref": 92,
        "brix_min": 10.0,
        "brix_max": 16.0,
        "brix_g": 0.25,
        "brix_0_default": 10.0,
        "qual_brix_target": 15.0,
        "SL_ref": 21,
        "firmness_min": 5.0,
        "firmness_0_default": 35,
        "qual_firmness_threshold": 10.0,
        "acidity_0_default": 0.8,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "orange": {
        "label": "Orange",
        "Tref_C": 5.0,
        "Ea_J": 42000,
        "k_firm_ref": 0.01,
        "beta_RH": 0.35,
        "RH_ref": 90,
        "brix_min": 11.0,
        "brix_max": 11.5,
        "brix_g": 0.01,
        "brix_0_default": 11.0,
        "qual_brix_target": 11.0,
        "SL_ref": 90,
        "firmness_min": 20.0,
        "firmness_0_default": 50,
        "qual_firmness_threshold": 35.0,
        "acidity_0_default": 1.0,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "banana": {
        "label": "Banana",
        "Tref_C": 14.0,
        "Ea_J": 65000,
        "k_firm_ref": 0.09,
        "beta_RH": 1.0,
        "RH_ref": 90,
        "brix_min": 5.0,
        "brix_max": 20.0,
        "brix_g": 0.5,
        "brix_0_default": 5.0,
        "qual_brix_target": 19.0,
        "SL_ref": 21,
        "firmness_min": 5.0,
        "firmness_0_default": 80,
        "qual_firmness_threshold": 15.0,
        "acidity_0_default": 0.4,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "pear": {
        "label": "Pear",
        "Tref_C": 2.0,
        "Ea_J": 54000,
        "k_firm_ref": 0.05,
        "beta_RH": 1.2,
        "RH_ref": 92,
        "brix_min": 11.0,
        "brix_max": 15.0,
        "brix_g": 0.25,
        "brix_0_default": 11.0,
        "qual_brix_target": 14.0,
        "SL_ref": 90,
        "firmness_min": 6.0,
        "firmness_0_default": 50,
        "qual_firmness_threshold": 12.0,
        "acidity_0_default": 0.3,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "grape": {
        "label": "Grape",
        "Tref_C": 2.0,
        "Ea_J": 45000,
        "k_firm_ref": 0.02,
        "beta_RH": 1.8,
        "RH_ref": 92,
        "brix_min": 16.0,
        "brix_max": 16.5,
        "brix_g": 0.01,
        "brix_0_default": 16.0,
        "qual_brix_target": 16.0,
        "SL_ref": 45,
        "firmness_min": 5.0,
        "firmness_0_default": 15,
        "qual_firmness_threshold": 8.0,
        "acidity_0_default": 0.6,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "fig": {
        "label": "Fig",
        "Tref_C": 2.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.11,
        "beta_RH": 1.8,
        "RH_ref": 95,
        "brix_min": 16.0,
        "brix_max": 20.0,
        "brix_g": 0.15,
        "brix_0_default": 16.0,
        "qual_brix_target": 19.0,
        "SL_ref": 7,
        "firmness_min": 1.0,
        "firmness_0_default": 8,
        "qual_firmness_threshold": 2.0,
        "acidity_0_default": 0.3,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
    "melon": {
        "label": "Melon",
        "Tref_C": 7.0,
        "Ea_J": 52000,
        "k_firm_ref": 0.06,
        "beta_RH": 0.9,
        "RH_ref": 90,
        "brix_min": 10.0,
        "brix_max": 14.0,
        "brix_g": 0.22,
        "brix_0_default": 10.0,
        "qual_brix_target": 13.5,
        "SL_ref": 21,
        "firmness_min": 5.0,
        "firmness_0_default": 20,
        "qual_firmness_threshold": 8.0,
        "acidity_0_default": 0.2,
        "acidity_min": 0.5,
        "k_acidity_ref": 0.02,
        "Ea_acidity_J": 55000,
        "qual_acidity_target": 1.0,
    },
}

MOLD_DEFAULTS = {
    "RH_mold_thr": 95.0,        # RH (%) from which significant risk starts
    "mold_rate_ref": 0.06,      # base rate (1/day) at Tref
    "mold_sens_RH": 10.0,       # sensitivity to RH surplus above threshold
    "mold_max_penalty": 0.80,   # maximum penalty (0..1)
    "Ea_mold_J": 45000.0,       # temperature sensitivity (Arrhenius)
}

MOLD_BY_FRUIT = {
    # Very sensitive
    "strawberry":   {"RH_mold_thr": 93.0, "mold_rate_ref": 0.22, "mold_sens_RH": 16.0, "mold_max_penalty": 0.95, "Ea_mold_J": 52000.0},
    "raspberry": {"RH_mold_thr": 93.0, "mold_rate_ref": 0.20, "mold_sens_RH": 16.0, "mold_max_penalty": 0.95, "Ea_mold_J": 52000.0},
    "fig":      {"RH_mold_thr": 93.0, "mold_rate_ref": 0.18, "mold_sens_RH": 14.0, "mold_max_penalty": 0.92, "Ea_mold_J": 50000.0},

    # Sensitive
    "blueberry":   {"RH_mold_thr": 94.0, "mold_rate_ref": 0.12, "mold_sens_RH": 14.0, "mold_max_penalty": 0.90, "Ea_mold_J": 48000.0},
    "cherry":    {"RH_mold_thr": 94.0, "mold_rate_ref": 0.10, "mold_sens_RH": 13.0, "mold_max_penalty": 0.85, "Ea_mold_J": 47000.0},
    "peach":   {"RH_mold_thr": 94.0, "mold_rate_ref": 0.10, "mold_sens_RH": 12.0, "mold_max_penalty": 0.85, "Ea_mold_J": 48000.0},
    "plum":    {"RH_mold_thr": 94.0, "mold_rate_ref": 0.09, "mold_sens_RH": 12.0, "mold_max_penalty": 0.82, "Ea_mold_J": 47000.0},

    # Medium
    "pear":      {"RH_mold_thr": 95.0, "mold_rate_ref": 0.07, "mold_sens_RH": 10.0, "mold_max_penalty": 0.75, "Ea_mold_J": 45000.0},
    "melon":     {"RH_mold_thr": 95.0, "mold_rate_ref": 0.08, "mold_sens_RH": 10.0, "mold_max_penalty": 0.78, "Ea_mold_J": 45000.0},
    "grape":       {"RH_mold_thr": 95.0, "mold_rate_ref": 0.10, "mold_sens_RH": 14.0, "mold_max_penalty": 0.90, "Ea_mold_J": 46000.0},

    # Low to medium (kiwis/apples)
    "kiwi_hayward": {"RH_mold_thr": 95.0, "mold_rate_ref": 0.05,  "mold_sens_RH": 9.0,  "mold_max_penalty": 0.65, "Ea_mold_J": 43000.0},
    "kiwi_baby":    {"RH_mold_thr": 95.0, "mold_rate_ref": 0.07,  "mold_sens_RH": 10.0, "mold_max_penalty": 0.75, "Ea_mold_J": 45000.0},
    "kiwi_gold":    {"RH_mold_thr": 95.0, "mold_rate_ref": 0.08,  "mold_sens_RH": 11.0, "mold_max_penalty": 0.78, "Ea_mold_J": 45000.0},
    "apple_golden":  {"RH_mold_thr": 95.0, "mold_rate_ref": 0.04,  "mold_sens_RH": 8.0,  "mold_max_penalty": 0.60, "Ea_mold_J": 42000.0},
    "apple_reineta": {"RH_mold_thr": 95.0, "mold_rate_ref": 0.05,  "mold_sens_RH": 9.0,  "mold_max_penalty": 0.65, "Ea_mold_J": 43000.0},
    "apple_gala":    {"RH_mold_thr": 95.0, "mold_rate_ref": 0.05,  "mold_sens_RH": 9.0,  "mold_max_penalty": 0.65, "Ea_mold_J": 43000.0},
    "apple_fuji":    {"RH_mold_thr": 95.0, "mold_rate_ref": 0.035, "mold_sens_RH": 8.0,  "mold_max_penalty": 0.55, "Ea_mold_J": 42000.0},
    "apple_granny_smith":  {"RH_mold_thr": 95.0, "mold_rate_ref": 0.03,  "mold_sens_RH": 7.5,  "mold_max_penalty": 0.50, "Ea_mold_J": 41000.0},
    "apple_red_delicious": {"RH_mold_thr": 95.0, "mold_rate_ref": 0.05,  "mold_sens_RH": 9.0,  "mold_max_penalty": 0.65, "Ea_mold_J": 43000.0},
    "apple_bravo_esmolfe": {"RH_mold_thr": 94.0, "mold_rate_ref": 0.09,  "mold_sens_RH": 12.0, "mold_max_penalty": 0.78, "Ea_mold_J": 46000.0},
    "apple_royal_gold":    {"RH_mold_thr": 95.0, "mold_rate_ref": 0.04,  "mold_sens_RH": 8.0,  "mold_max_penalty": 0.60, "Ea_mold_J": 42000.0},
    "apple_pink_lady":     {"RH_mold_thr": 95.0, "mold_rate_ref": 0.03,  "mold_sens_RH": 7.5,  "mold_max_penalty": 0.50, "Ea_mold_J": 41000.0},
    "apple_jonagold":      {"RH_mold_thr": 95.0, "mold_rate_ref": 0.05,  "mold_sens_RH": 9.0,  "mold_max_penalty": 0.65, "Ea_mold_J": 43000.0},
    "apple_alcobaca":      {"RH_mold_thr": 95.0, "mold_rate_ref": 0.05,  "mold_sens_RH": 9.0,  "mold_max_penalty": 0.65, "Ea_mold_J": 43000.0},

    # Low (citrus)
    "orange": {"RH_mold_thr": 96.0, "mold_rate_ref": 0.03, "mold_sens_RH": 8.0, "mold_max_penalty": 0.50, "Ea_mold_J": 42000.0},
}

PACKAGING_FACTORS = {
   "Granel (Sem embalagem)": 1.0,
   "Caixa de Cartão Aberta": 0.85,
   "Saco Plástico Perfurado": 0.45,
   "MAP (Atmosfera Modificada) / Plástico Selado": 0.10,
   "Cardboard": 0.85,
   "Plastic_Perforated": 0.45,
   "MAP": 0.10,
   "Bulk": 1.0
}

STAKEHOLDER_PROFILES = {
    "Producer / Exporter": {
        "min_quality": 35,
        "firm_multiplier": 1.75,
        "mold_limit": 0.01,
        "brix_multiplier": 0.3,
        "ratio_multiplier": 0.5
    },
    "Producer": {
        "min_quality": 35,
        "firm_multiplier": 1.75,
        "mold_limit": 0.01,
        "brix_multiplier": 0.3,
        "ratio_multiplier": 0.5
    },
    "Retailer (Grocery Store)": {
        "min_quality": 65,
        "firm_multiplier": 1.0,
        "mold_limit": 0.03,
        "brix_multiplier": 0.95,
        "ratio_multiplier": 0.9
    },
    "Retailer": {
        "min_quality": 65,
        "firm_multiplier": 1.0,
        "mold_limit": 0.03,
        "brix_multiplier": 0.95,
        "ratio_multiplier": 0.9
    },
    "Processor": {
        "min_quality": 20,
        "firm_multiplier": 0.15,
        "mold_limit": 0.08,
        "brix_multiplier": 1.0,
        "ratio_multiplier": 1.0
    },
    "Industry (Juices/Jellies)": {
        "min_quality": 20,       
        "firm_multiplier": 0.15,
        "mold_limit": 0.08,
        "brix_multiplier": 1.0,
        "ratio_multiplier": 1.0 
    }
}

# Auto-initialize mold parameters into preset dictionaries
for k in PRESETS_ACADEMIC:
    for kk, vv in MOLD_DEFAULTS.items():
        PRESETS_ACADEMIC[k].setdefault(kk, vv)
    if k in MOLD_BY_FRUIT:
        PRESETS_ACADEMIC[k].update(MOLD_BY_FRUIT[k])

for k in PRESETS_SOFIA:
    for kk, vv in MOLD_DEFAULTS.items():
        PRESETS_SOFIA[k].setdefault(kk, vv)
    if k in MOLD_BY_FRUIT:
        PRESETS_SOFIA[k].update(MOLD_BY_FRUIT[k])


def get_preset(fruit_key: str) -> dict:
    """Returns biological parameter preset for a given fruit/variety key."""
    if fruit_key in PRESETS_ACADEMIC:
        return PRESETS_ACADEMIC[fruit_key]
    if fruit_key in PRESETS_SOFIA:
        return PRESETS_SOFIA[fruit_key]
    raise KeyError(f"Preset '{fruit_key}' not found.")
